### ISSUE TITLE
Frontend Development | `Conduct UI/UX testing`

### ISSUE THREAD

**Issue by 4D-Coder** [4D-Coder/WanderWattz-EMS#13]
- [ ] Perform usability testing with a group of potential users.
- [ ] Document feedback and implement necessary UI adjustments.
- [ ] Test mobile responsiveness in various devices and browsers.
