### ISSUE TITLE
Planning & Design  | `Plan the database schema`

### ISSUE THREAD

**Issue by 4D-Coder** [4D-Coder/WanderWattz-EMS#3]
- [ ] Draw an entity-relationship diagram.
- [ ] Document table structures, including columns and data types.
- [ ] Define and document database relationships (foreign keys, one-to-many, many-to-many).
